<?php echo $this->nodeNavigation('MJ', 'list')->render() ?>

<?php if ($this->paginator->count()) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
            	<th>Geplanter Versand</th>
            	<th>Status</th>
                <th>Betreff</th>
                <th>Channels</th>
            </tr>
        </thead>
        <tbody class="rowlink" data-link="row">
            <?php foreach ($this->paginator as $entity) : ?>
                <tr <?php if (! $entity->isEnabled()) echo 'class="danger"' ?>>
                	<td>
                		<?php echo $this->dateFormat($entity->getTimestampScheduled(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                	</td>
                	<td>
                		<?php echo $entity->getStatus(true) ?>
                	</td>
                    <td>
                        <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
	                        <?php echo $this->escapeHtml($entity->getNews()->getSubject()) ?>
	                    </a>
                    </td>
                    <td>
                    	<?php
                            $channels = array();
                            foreach ($entity->getChannels() as $channel)
                                $channels[] = $channel->getTitle();
                            echo $this->escapeHtml(implode(', ', $channels));
                    	?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl() ?>
<?php else : ?>
    <p>Keine Einträge.</p>
<?php endif ?>