<?php echo $this->nodeNavigation('ML', 'list')->render() ?>

<?php if ($this->paginator->count()) : ?>
    <table class="table _table-hover">
        <thead>
            <tr>
                <th>Betreff</th>
                <th>Empfänger</th>
                <th>Geplant</th>
                <th>Abgeschlossen</th>
            </tr>
        </thead>
        <tbody >
            <?php foreach ($this->paginator as $entity) : ?>
                <tr <?php 
                        if ($entity->isEnabled() && $entity->getTimestampScheduled() && ! $entity->getTimestampSent()) {
                            echo 'class="warning"';
                        } elseif ($entity->getTimestampSent()) {
                            echo 'class="success"';
                        }
                    ?>>
                    <td>
	                        <?php echo $this->escapeHtml($entity->getSubject()) ?>
                    </td>
                    <td>
                    	<?php
                            $titles = array();
                            foreach ($entity->getChannels() as $channel)
                                $titles[] = $channel->getTitle();
                            echo $this->escapeHtml(implode(', ', $titles)); 
                    	?>
                    </td>
                    <td>
                    	<?php echo $this->dateFormat($entity->getTimestampScheduled(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                    </td>
                    <td>
                    	<?php echo $this->dateFormat($entity->getTimestampSent(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                    </td>
                    <td>
                    	<div class="dropdown">
                    		<button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
                    			<span class="glyphicon glyphicon-cog"></span>
	                    		<span class="caret"></span>
                    		</button>
                    		<ul class="dropdown-menu">
                    			<li>
                    				<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
                    					Bearbeiten
                    				</a>
                    			</li>
                    			<li>
                    				<a href="<?php echo $this->url('kofus_mailer', array('controller' => 'mail', 'action' => 'reset', 'id' => $entity->getNodeId())) ?>">
                    					Zurücksetzen
                    				</a>
                    			</li>
                    			<li>
                    				<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'delete', 'id' => $entity->getNodeId())) ?>">
                    					Löschen
                    				</a>
                    			</li>
                    		</ul>
                    	</div>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl() ?>
<?php else : ?>
    <p>Keine Einträge.</p>
<?php endif ?>