<?php echo $this->nodeNavigation('ML', 'list')->render() ?>

<?php echo $this->partial('kofus/mailer/mail/tabs.phtml') ?>

<?php if ($this->paginator->count()) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Betreff</th>
                <th>Empfänger</th>
                <th>Datum</th>
            </tr>
        </thead>
        <tbody class="rowlink" data-link="row">
            <?php foreach ($this->paginator as $entity) : ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('kofus_mailer', array('controller' => 'mail', 'action' => 'preview', 'id' => $entity->getNodeId())) ?>" target="_blank">
	                        <?php echo $this->escapeHtml($entity->getSubject()) ?>
	                    </a>
                    </td>
                    <td>
                    	<?php echo $this->escapeHtml($entity->getHeaders()->get('to')->toString())	?>
                    </td>
                    <td>
                    	<?php echo $this->dateFormat($entity->getTimestampSent(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl() ?>
<?php else : ?>
    <p>Keine Einträge.</p>
<?php endif ?>