<?php echo $this->nodeNavigation($this->entity, 'view', $this->entity->getTitle())->render() ?>

<?php if ($this->subscriptions) : ?>
	<h3>Abonnenten</h3>
	<table class="table">
		<tbody>
        	<?php foreach ($this->subscriptions as $subscription) : ?>
        		<?php 
                    $subscriber = $this->nodes()->getNode($subscription->getSubscriberId());
                    if (! $subscriber instanceof \Kofus\Mailer\NewsSubscriberInterface) continue;
        		?>
        		<tr>
        			<td>
        				<?php echo $this->escapeHtml($subscriber->getEmailAddress()) ?>
        			</td>
        			<td>
        				<?php echo $this->escapeHtml($subscriber) ?>
        			</td>
        		</tr>
        	<?php endforeach ?>
    	</tbody>
	</table>
<?php endif ?>
