<?php echo $this->nodeNavigation($this->entity, 'view', $this->entity->getTitle())->render() ?>

<h3>Abonnenten</h3>
<?php if (count($this->subscriptions)) : ?>
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>E-Mail</th>
				<th>Abonniert am</th>
			</tr>
		</thead>
		<tbody>
        	<?php foreach ($this->subscriptions as $subscription) : ?>
        		<?php 
                    $subscriber = $subscription->getSubscriber();
        		?>
        		<tr <?php if (! $subscription->getTimestampActivation()) echo 'class="warning"'?>>
        			<td>
        				<?php echo $this->escapeHtml($subscriber->getName()) ?>
        			</td>
        			<td>
        				<?php echo $this->escapeHtml($subscriber->getEmailAddress()) ?>
        			</td>
        			<td>
        				<?php echo $this->dateFormat($subscription->getTimestampActivation(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
        			</td>
        			<td>
        				<div class="dropdown">
        					<button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
        						<span class="glyphicon glyphicon-cog"></span>
        						<span class="caret"></span>
        					</button>
        					<ul class="dropdown-menu">
        						<li>
        							<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $subscriber->getNodeId())) ?>">
        								Abonnent bearbeiten
        							</a>
        						</li>
        						<li>
        							<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'delete', 'id' => $subscription->getNodeId())) ?>">
        								Abonnement löschen
        							</a>
        						</li>
        						
        					</ul>
        				</div>
        			</td>
        		</tr>
        	<?php endforeach ?>
    	</tbody>
	</table>
	<?php echo $this->paginationControl($this->subscriptions) ?>
<?php else : ?>
	<p>Keine Einträge.</p>	
<?php endif ?>
