<div class="row">

    <div class="col-md-9">
    	<h1><?php echo $this->escapeHtml($this->entity->getSubject()) ?></h1>
    	<?php echo $this->entity->getContentHtml() ?>
    	
    </div>
    <div class="col-md-3">
    	  <div class="list-group">
    	      <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
    	          <?php echo $this->translate('Close') ?>
    	      </a>
    	      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $this->entity->getNodeId()), array(), true) ?>" class="list-group-item">
    	          <i class="glyphicon glyphicon-pencil"></i>
    	          <?php echo $this->translate('Edit') ?>
    	      </a>
    	      <a href="<?php echo $this->url('kofus_mailer', array('controller' => 'news', 'action' => 'preview', 'id' => $this->entity->getNodeId()), array(), true) ?>" class="list-group-item" target="_blank">
    	          <i class="glyphicon glyphicon-preview"></i>
    	          Vorschau
    	      </a>
    	      
    	  </div>
    </div>

</div>