<?php echo $this->nodeNavigation('SCB', 'list', 'Abonnenten (' . $this->paginator->getTotalItemCount() . ')')->render() ?>

<?php if ($this->paginator->count()) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>E-Mail</th>
                <th>Abonnements</th>
                <th>Abonnent seit</th>
            </tr>
        </thead>
        <tbody class="rowlink" data-link="row">
            <?php foreach ($this->paginator as $entity) : ?>
                <tr>
                	<td>
                		<?php echo $this->escapeHtml($entity->getName()) ?>
                	</td>
                    <td>
                        <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
	                        <?php echo $this->escapeHtml($entity->getEmailAddress()) ?>
	                    </a>
                    </td>
                    <td>
                    	<?php
                            $subscriptions = $this->nodes()->createQueryBuilder('SCP')
                                ->where('n.subscriber = :subscriber')
                                ->setParameter('subscriber', $entity)
                                ->andWhere('n.timestampActivation IS NOT NULL')
                                ->getQuery()->getResult();
                            $channels = array();
                            foreach ($subscriptions as $subscription) {
                                $channels[] = $subscription->getChannel()->getTitle();
                            }
                            echo $this->escapeHtml(implode(', ', $channels));
                    	?>
                    </td>
                    <td>
                    	<?php echo $this->dateFormat($entity->getTimestampCreated(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl() ?>
<?php else : ?>
    <p>Keine Einträge.</p>
<?php endif ?>