<?php echo $this->nodeNavigation('SCB', 'list')->render() ?>

<?php if ($this->paginator->count()) : ?>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>E-Mail</th>
                <th>Abonnements</th>
            </tr>
        </thead>
        <tbody class="rowlink" data-link="row">
            <?php foreach ($this->paginator as $entity) : ?>
                <tr>
                	<td>
                		<?php echo $this->escapeHtml($entity->getName()) ?>
                	</td>
                    <td>
                        <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
	                        <?php echo $this->escapeHtml($entity->getEmailAddress()) ?>
	                    </a>
                    </td>
                    <td>
                    	
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl() ?>
<?php else : ?>
    <p>Keine Einträge.</p>
<?php endif ?>