<?php echo $this->nodeNavigation($this->subscriber, 'view', $this->subscriber->getEmailAddress())->render() ?>


<h2>Abonnierte News Channels</h2>

<?php if ($this->subscriptions) : ?>
	<table class="table">
		<thead>
			<tr>
				<th>
					Channel
				</th>
				<th>
					Status
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->subscriptions as $subscription) : ?>
				<tr <?php
				    switch ($subscription->getStatus()) {
				        case 'pending':
				            print 'class="warning"';
				            break;
				        
				    }
				
				?>>
					<td>
						<?php echo $this->escapeHtml($subscription->getChannel()->getTitle()) ?>
					</td>
					<td>
						<?php echo $this->escapeHtml($subscription->getStatus(true)) ?>
					</td>
				</tr>
			<?php endforeach ?>
		</tbody>
	</table>
<?php else : ?>
	<p>Keine Einträge.</p>
<?php endif ?>
