<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
        <h1>Einstellungen bearbeiten</h1>
        <?php if ($this->msgs) : ?>
        	<p>Vielen Dank. Ihre Einstellungen wurden gespeichert:</p>
        	<ul> 
            	<?php foreach ($this->msgs as $msg) : ?>
            		<li>
            			<?php echo $this->escapeHtml($msg) ?>
            		</li>
            	<?php endforeach ?>
        	</ul>
        <?php else : ?>
            <p>Benachrichtigungen für <b><?php echo $this->escapeHtml($this->subscriber->getEmailAddress()) ?></b>:</p>
            <?php echo $this->form($this->form) ?>
        <?php endif ?>
    </div>
    <div class="col-md-3"></div>
</div>